# https://docs.github.com/en/code-security/supply-chain-security/configuration-options-for-dependency-updates
version: 2

updates:

- package-ecosystem: mix
  directory: "/"
  schedule:
    interval: daily # default: 05:00 UTC

- package-ecosystem: github-actions
  directory: "/"
  schedule:
    interval: daily # default: 05:00 UTC
