name: CI
env:
  MIX_ENV: ci
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  CC: clang

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-20.04
    name: OTP ${{matrix.otp}} | Elixir ${{matrix.elixir}} | ${{matrix.cc}}

    strategy:
      matrix:
        otp: [23.3, 22.3]
        elixir: [1.11.4, 1.10.4]
        cc: [gcc, clang]

    steps:
    - uses: actions/checkout@v2.3.4
    - uses: actions/cache@v2.1.5
      with:
        path: |
          deps
          _build
        key: ${{ runner.os }}-${{matrix.otp}}-${{matrix.elixir}}-${{matrix.cc}}-mix-${{ hashFiles(format('{0}{1}', github.workspace, '/mix.lock')) }}
        restore-keys: |
          ${{ runner.os }}-mix-

    - uses: erlef/setup-elixir@v1.7
      with:
        otp-version: ${{matrix.otp}}
        elixir-version: ${{matrix.elixir}}

    - name: Install Dependencies
      run: mix deps.get

    - name: Compile project
      run: mix compile
      env:
        CC: ${{ matrix.cc }}

    - name: Run tests
      run: mix test

    - name: Run quality steps
      run: |
        mix credo --strict
        mix inch.report
        mix hex.outdated

    - name: Report coverage
      run: mix coveralls.github
      # even if we cannot send the report, the build is still okay
      continue-on-error: true
